/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package scrumprojekt;

import java.awt.BorderLayout;
import java.awt.Button;
import java.awt.Component;
import javax.swing.BoxLayout;
import javax.swing.JPanel;
import oru.inf.InfDB;



/**
 *ygh
 * @author Joakim
 */
public class EducationFrame extends javax.swing.JFrame {
    
    private InfDB db;
    private int user_id;
    /**
     * Creates new form EducationFrame
     */
    public EducationFrame(InfDB db, int user_id) {
        initComponents();
        this.db = db;
        this.user_id = user_id;
        
        BoxLayoutDemo.addComponentsToPane(jpContainer);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        educationHeader = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        lblCreateNewPost = new javax.swing.JLabel();
        educationforumPosts = new javax.swing.JPanel();
        jpContainer = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        educationHeader.setBackground(new java.awt.Color(50, 121, 184));
        educationHeader.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        educationHeader.setPreferredSize(new java.awt.Dimension(1170, 100));

        jLabel25.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(250, 249, 246));
        jLabel25.setText("Education forum");

        lblCreateNewPost.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblCreateNewPost.setForeground(new java.awt.Color(250, 249, 246));
        lblCreateNewPost.setText("New Post +");
        lblCreateNewPost.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCreateNewPostMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout educationHeaderLayout = new javax.swing.GroupLayout(educationHeader);
        educationHeader.setLayout(educationHeaderLayout);
        educationHeaderLayout.setHorizontalGroup(
            educationHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(educationHeaderLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 662, Short.MAX_VALUE)
                .addComponent(lblCreateNewPost)
                .addGap(66, 66, 66))
        );
        educationHeaderLayout.setVerticalGroup(
            educationHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(educationHeaderLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(educationHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(lblCreateNewPost))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        educationforumPosts.setPreferredSize(new java.awt.Dimension(1170, 540));

        javax.swing.GroupLayout jpContainerLayout = new javax.swing.GroupLayout(jpContainer);
        jpContainer.setLayout(jpContainerLayout);
        jpContainerLayout.setHorizontalGroup(
            jpContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1170, Short.MAX_VALUE)
        );
        jpContainerLayout.setVerticalGroup(
            jpContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 547, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout educationforumPostsLayout = new javax.swing.GroupLayout(educationforumPosts);
        educationforumPosts.setLayout(educationforumPostsLayout);
        educationforumPostsLayout.setHorizontalGroup(
            educationforumPostsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        educationforumPostsLayout.setVerticalGroup(
            educationforumPostsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, educationforumPostsLayout.createSequentialGroup()
                .addComponent(jpContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(educationHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(educationforumPosts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(educationHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(educationforumPosts, javax.swing.GroupLayout.DEFAULT_SIZE, 553, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblCreateNewPostMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCreateNewPostMouseClicked
        // TODO add your handling code here:
        new CreateNewPost(db, user_id, 'E').setVisible(true);
        dispose();
    }//GEN-LAST:event_lblCreateNewPostMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EducationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EducationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EducationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EducationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EducationFrame().setVisible(true);
            }
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel educationHeader;
    private javax.swing.JPanel educationforumPosts;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JPanel jpContainer;
    private javax.swing.JLabel lblCreateNewPost;
    // End of variables declaration//GEN-END:variables
}
