/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package scrumprojekt;

import java.awt.Color;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.BorderFactory;
import oru.inf.InfDB;

/**
 *
 * @author Joakim
 */
public class MainWindow extends javax.swing.JFrame {

    private InfDB db;
    private int user_id;

    /**
     * Creates new form MainWindow
     */
    public MainWindow(InfDB db, int user_id) {
        initComponents();
        this.db = db;
        this.user_id = user_id;
        this.setLocationRelativeTo(null);
        setResizable(false);
        lblAdmin.setVisible(false);
        getRootPane().setBorder(BorderFactory.createMatteBorder(4, 4, 4, 4, Color.black));
        clock();

        if (DBFetcher.fetchRankFromUser(db, user_id) == 5 || DBFetcher.fetchRankFromUser(db, user_id) == 4 || DBFetcher.fetchRankFromUser(db, user_id) == 3) {
            lblAdmin.setVisible(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelHeader = new javax.swing.JPanel();
        panelOpenEducation = new javax.swing.JPanel();
        labelOpenEducation = new javax.swing.JLabel();
        panelOpenSocial = new javax.swing.JPanel();
        labelOpenSocial = new javax.swing.JLabel();
        panelOpenResearch = new javax.swing.JPanel();
        labelOpenResearch = new javax.swing.JLabel();
        lblAdmin = new javax.swing.JLabel();
        lblExit = new javax.swing.JLabel();
        lblLogOut = new javax.swing.JLabel();
        panelHome = new javax.swing.JPanel();
        labelWelcome = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(250, 249, 246));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(1170, 700));

        panelHeader.setBackground(new java.awt.Color(50, 121, 184));
        panelHeader.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        panelOpenEducation.setBackground(new java.awt.Color(50, 121, 184));
        panelOpenEducation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelOpenEducationMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelOpenEducationMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelOpenEducationMouseExited(evt);
            }
        });

        labelOpenEducation.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        labelOpenEducation.setForeground(new java.awt.Color(250, 249, 246));
        labelOpenEducation.setText("Education");
        labelOpenEducation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelOpenEducationMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelOpenEducationMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelOpenEducationMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelOpenEducationLayout = new javax.swing.GroupLayout(panelOpenEducation);
        panelOpenEducation.setLayout(panelOpenEducationLayout);
        panelOpenEducationLayout.setHorizontalGroup(
            panelOpenEducationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelOpenEducationLayout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addComponent(labelOpenEducation)
                .addGap(55, 55, 55))
        );
        panelOpenEducationLayout.setVerticalGroup(
            panelOpenEducationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelOpenEducationLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(labelOpenEducation)
                .addContainerGap())
        );

        panelOpenSocial.setBackground(new java.awt.Color(50, 121, 184));
        panelOpenSocial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelOpenSocialMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelOpenSocialMouseExited(evt);
            }
        });

        labelOpenSocial.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        labelOpenSocial.setForeground(new java.awt.Color(250, 249, 246));
        labelOpenSocial.setText("Social");

        javax.swing.GroupLayout panelOpenSocialLayout = new javax.swing.GroupLayout(panelOpenSocial);
        panelOpenSocial.setLayout(panelOpenSocialLayout);
        panelOpenSocialLayout.setHorizontalGroup(
            panelOpenSocialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOpenSocialLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(labelOpenSocial)
                .addContainerGap(83, Short.MAX_VALUE))
        );
        panelOpenSocialLayout.setVerticalGroup(
            panelOpenSocialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelOpenSocialLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(labelOpenSocial)
                .addContainerGap())
        );

        panelOpenResearch.setBackground(new java.awt.Color(50, 121, 184));
        panelOpenResearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelOpenResearchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelOpenResearchMouseExited(evt);
            }
        });

        labelOpenResearch.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        labelOpenResearch.setForeground(new java.awt.Color(250, 249, 246));
        labelOpenResearch.setText("Research");

        javax.swing.GroupLayout panelOpenResearchLayout = new javax.swing.GroupLayout(panelOpenResearch);
        panelOpenResearch.setLayout(panelOpenResearchLayout);
        panelOpenResearchLayout.setHorizontalGroup(
            panelOpenResearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelOpenResearchLayout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addComponent(labelOpenResearch)
                .addGap(58, 58, 58))
        );
        panelOpenResearchLayout.setVerticalGroup(
            panelOpenResearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelOpenResearchLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(labelOpenResearch)
                .addContainerGap())
        );

        lblAdmin.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblAdmin.setForeground(new java.awt.Color(250, 249, 246));
        lblAdmin.setText("Admin");
        lblAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAdminMouseClicked(evt);
            }
        });

        lblExit.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblExit.setForeground(new java.awt.Color(250, 249, 246));
        lblExit.setText("Exit");
        lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitMouseClicked(evt);
            }
        });

        lblLogOut.setBackground(new java.awt.Color(250, 249, 246));
        lblLogOut.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblLogOut.setForeground(new java.awt.Color(250, 249, 246));
        lblLogOut.setText("Log out");
        lblLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogOutMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelHeaderLayout = new javax.swing.GroupLayout(panelHeader);
        panelHeader.setLayout(panelHeaderLayout);
        panelHeaderLayout.setHorizontalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeaderLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblAdmin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelOpenEducation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79)
                .addComponent(panelOpenResearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addComponent(panelOpenSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(149, 149, 149)
                .addGroup(panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblExit)
                    .addComponent(lblLogOut))
                .addGap(29, 29, 29))
        );
        panelHeaderLayout.setVerticalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeaderLayout.createSequentialGroup()
                .addGap(0, 15, Short.MAX_VALUE)
                .addGroup(panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelHeaderLayout.createSequentialGroup()
                        .addComponent(lblExit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblLogOut))
                    .addGroup(panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelOpenEducation, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(panelOpenResearch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(panelOpenSocial, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHeaderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblAdmin)
                .addContainerGap())
        );

        panelHome.setBackground(new java.awt.Color(250, 249, 246));
        panelHome.setPreferredSize(new java.awt.Dimension(1170, 650));

        labelWelcome.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        labelWelcome.setText("Welcome to Örebro University Informatics Portal");

        lblTime.setFont(new java.awt.Font("Georgia", 0, 24)); // NOI18N
        lblTime.setText("Time");

        lblDate.setFont(new java.awt.Font("Georgia", 0, 24)); // NOI18N
        lblDate.setText("Date");

        javax.swing.GroupLayout panelHomeLayout = new javax.swing.GroupLayout(panelHome);
        panelHome.setLayout(panelHomeLayout);
        panelHomeLayout.setHorizontalGroup(
            panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHomeLayout.createSequentialGroup()
                .addGroup(panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelHomeLayout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(labelWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 960, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelHomeLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTime))
                    .addGroup(panelHomeLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblDate)))
                .addGap(124, 124, 124))
        );
        panelHomeLayout.setVerticalGroup(
            panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHomeLayout.createSequentialGroup()
                .addComponent(lblTime, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDate)
                .addGap(80, 80, 80)
                .addComponent(labelWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(484, 484, 484))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelHome, javax.swing.GroupLayout.DEFAULT_SIZE, 1194, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelHome, javax.swing.GroupLayout.PREFERRED_SIZE, 731, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAdminMouseClicked
        new AdminFrame(db, user_id).setVisible(true);
        dispose();
    }//GEN-LAST:event_lblAdminMouseClicked

    private void panelOpenResearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelOpenResearchMouseExited
        panelOpenResearch.setBackground(new Color(50, 121, 184));
    }//GEN-LAST:event_panelOpenResearchMouseExited

    private void panelOpenResearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelOpenResearchMouseEntered
        panelOpenResearch.setBackground(new Color(77, 146, 208));
    }//GEN-LAST:event_panelOpenResearchMouseEntered

    private void panelOpenSocialMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelOpenSocialMouseExited
        panelOpenSocial.setBackground(new Color(50, 121, 184));
    }//GEN-LAST:event_panelOpenSocialMouseExited

    private void panelOpenSocialMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelOpenSocialMouseEntered
        panelOpenSocial.setBackground(new Color(77, 146, 208));
    }//GEN-LAST:event_panelOpenSocialMouseEntered

    private void panelOpenEducationMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelOpenEducationMouseExited
        panelOpenEducation.setBackground(new Color(50, 121, 184));
    }//GEN-LAST:event_panelOpenEducationMouseExited

    private void panelOpenEducationMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelOpenEducationMouseEntered
        panelOpenEducation.setBackground(new Color(77, 146, 208));
    }//GEN-LAST:event_panelOpenEducationMouseEntered

    private void labelOpenEducationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelOpenEducationMouseClicked
        new EducationFrame(db, user_id).setVisible(true);
        dispose();
    }//GEN-LAST:event_labelOpenEducationMouseClicked

    private void panelOpenEducationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelOpenEducationMouseClicked

        new EducationFrame(db, user_id).setVisible(true);
        dispose();
    }//GEN-LAST:event_panelOpenEducationMouseClicked

    private void labelOpenEducationMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelOpenEducationMouseEntered
        panelOpenEducation.setBackground(new Color(77, 146, 208));
    }//GEN-LAST:event_labelOpenEducationMouseEntered

    private void labelOpenEducationMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelOpenEducationMouseExited
        panelOpenEducation.setBackground(new Color(50, 121, 184));
    }//GEN-LAST:event_labelOpenEducationMouseExited

    private void lblExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblExitMouseClicked

    private void lblLogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogOutMouseClicked
        new LoginFrame().setVisible(true);
        dispose();
    }//GEN-LAST:event_lblLogOutMouseClicked

    public void clock() {
        Thread th = new Thread() {
            public void run() {
                try {
                    for (;;) {
                        Calendar cl = new GregorianCalendar();
                        int day = cl.get(Calendar.DAY_OF_MONTH);
                        int month = cl.get(Calendar.MONTH) + 1;
                        int year = cl.get(Calendar.YEAR);

                        int second = cl.get(Calendar.SECOND);
                        int min = cl.get(Calendar.MINUTE);
                        int hour = cl.get(Calendar.HOUR);
                        int am_pm = cl.get(Calendar.AM_PM);

                        String d_n = "";
                        if (am_pm == 1) {
                            d_n = "PM";
                        } else {
                        }
                       if (hour == 0) {
                           hour = 12;
                       } else {
                           hour = cl.get(Calendar.HOUR);
                       }
                        lblTime.setText("" + hour + ":" + min + ":" + second + " " + d_n + "");
                        lblDate.setText("" + day + "/" + month + "/" + year + "");
                    }
                } catch (Exception ex) {
                    ex.printStackTrace();
                }
            }
        };
        th.start();
    }
    /**
     * // * @param args the command line arguments //
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
// /*java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MainWindow(db).setVisible(true);
//            }
//        });*/
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelOpenEducation;
    private javax.swing.JLabel labelOpenResearch;
    private javax.swing.JLabel labelOpenSocial;
    private javax.swing.JLabel labelWelcome;
    private javax.swing.JLabel lblAdmin;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblExit;
    private javax.swing.JLabel lblLogOut;
    private javax.swing.JLabel lblTime;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JPanel panelHome;
    private javax.swing.JPanel panelOpenEducation;
    private javax.swing.JPanel panelOpenResearch;
    private javax.swing.JPanel panelOpenSocial;
    // End of variables declaration//GEN-END:variables
}
