/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package scrumprojekt;

import java.util.HashMap;
import oru.inf.InfDB;

/**
 *
 * @author Joakim
 */
public class postPanel extends javax.swing.JPanel {

    private InfDB db;
    private int post_id;
    private HashMap<String,String> post;
    private HashMap<String,String> user;
    /**
     * Creates new form postPanel
     */
    public postPanel(InfDB db, int post_id) {
        initComponents();
        this.db = db;
        this.post_id = post_id;
        updatePanel();
        
    }
    
    public void updatePanel() {
        post = DBFetcher.fetchPost(db, this.post_id);
        user = DBFetcher.fetchUser(db, Integer.parseInt(post.get("EMPLOYEE_IDEMPLOYEE")));
        
        headlinePostOne.setText(post.get("HEADLINE"));
        datePostOne.setText(post.get("POSTDATE"));
        authorPostOne.setText(user.get("FIRSTNAME") + " " + user.get("LASTNAME"));
        
        String postText = post.get("TEXT");
        int postTextLength = postText.length();
        if(postTextLength > 70) {
            lblText.setText(String.copyValueOf(post.get("TEXT").toCharArray(), 0, 70) + "...");
        } else {
            lblText.setText(String.copyValueOf(post.get("TEXT").toCharArray(), 0, postTextLength));
        }
        
        
        
        this.setVisible(true);
    }
    
    public int getPostId() {
        return post_id;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        postOne = new javax.swing.JPanel();
        headlinePostOne = new javax.swing.JLabel();
        imagePostOne = new javax.swing.JLabel();
        authorPostOne = new javax.swing.JLabel();
        datePostOne = new javax.swing.JLabel();
        lastReplyPostOne = new javax.swing.JLabel();
        dateLastReplyPostOne = new javax.swing.JLabel();
        lblText = new javax.swing.JLabel();

        postOne.setBackground(new java.awt.Color(250, 249, 246));
        postOne.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        headlinePostOne.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        headlinePostOne.setText("Headline:");

        imagePostOne.setText("IMAGE");

        authorPostOne.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        authorPostOne.setText("Author");

        datePostOne.setText("Date and time");

        lastReplyPostOne.setText("Last reply");

        dateLastReplyPostOne.setText("Date and time ");

        lblText.setText("jLabel1");

        javax.swing.GroupLayout postOneLayout = new javax.swing.GroupLayout(postOne);
        postOne.setLayout(postOneLayout);
        postOneLayout.setHorizontalGroup(
            postOneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(postOneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imagePostOne)
                .addGap(17, 17, 17)
                .addGroup(postOneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(headlinePostOne)
                    .addGroup(postOneLayout.createSequentialGroup()
                        .addComponent(authorPostOne)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(datePostOne)))
                .addGap(49, 49, 49)
                .addComponent(lblText, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, Short.MAX_VALUE)
                .addGroup(postOneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateLastReplyPostOne)
                    .addComponent(lastReplyPostOne))
                .addContainerGap())
        );
        postOneLayout.setVerticalGroup(
            postOneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(postOneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(postOneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(postOneLayout.createSequentialGroup()
                        .addGroup(postOneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(headlinePostOne)
                            .addComponent(imagePostOne))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addGroup(postOneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(datePostOne)
                            .addComponent(authorPostOne)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, postOneLayout.createSequentialGroup()
                        .addGroup(postOneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(postOneLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(lastReplyPostOne)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dateLastReplyPostOne))
                            .addComponent(lblText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(postOne, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(postOne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel authorPostOne;
    private javax.swing.JLabel dateLastReplyPostOne;
    private javax.swing.JLabel datePostOne;
    private javax.swing.JLabel headlinePostOne;
    private javax.swing.JLabel imagePostOne;
    private javax.swing.JLabel lastReplyPostOne;
    private javax.swing.JLabel lblText;
    private javax.swing.JPanel postOne;
    // End of variables declaration//GEN-END:variables
}
