/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package scrumprojekt;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import oru.inf.InfDB;

/**
 *
 * @author Joakim
 */
public class postPanel extends javax.swing.JPanel {

    private Connection conn;
    private int post_id;
    private ResultSet post;
    private ResultSet user;
    /**
     * Creates new form postPanel
     */
    public postPanel(Connection conn, int post_id) {
        initComponents();
        this.conn = conn;
        this.post_id = post_id;
        updatePanel();
        //jLabel1.setLocation(27, 20);
        
        
    }
    
    public void updatePanel() {
        try {
            post = DBFetcher.fetchPost(conn, this.post_id);
            post.next();
            user = DBFetcher.fetchUser(conn, post.getInt("EMPLOYEE_IDEMPLOYEE"));
            user.next();
            
            headlinePostOne.setText(post.getString("HEADLINE"));
            datePostOne.setText(post.getString("POSTDATE"));
            authorPostOne.setText(user.getString("FIRSTNAME") + " " + user.getString("LASTNAME"));
            lblCategory.setText(post.getString("TAG"));
            
            String postText = post.getString("TEXT");
            int postTextLength = postText.length();
            if(postTextLength > 70) {
                lblText.setText(String.copyValueOf(post.getString("TEXT").toCharArray(), 0, 70) + "...");
            } else {
                lblText.setText(String.copyValueOf(post.getString("TEXT").toCharArray(), 0, postTextLength));
            }
            
            
            
            this.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(postPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public int getPostId() {
        return post_id;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        postOne = new javax.swing.JPanel();
        headlinePostOne = new javax.swing.JLabel();
        authorPostOne = new javax.swing.JLabel();
        datePostOne = new javax.swing.JLabel();
        lastReplyPostOne = new javax.swing.JLabel();
        dateLastReplyPostOne = new javax.swing.JLabel();
        lblText = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblCategory = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        postOne.setBackground(new java.awt.Color(250, 249, 246));
        postOne.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        headlinePostOne.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        headlinePostOne.setText("Headline:");

        authorPostOne.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        authorPostOne.setText("Author");

        datePostOne.setText("Date and time");

        lastReplyPostOne.setText("Last reply");

        dateLastReplyPostOne.setText("Date and time ");

        lblText.setText("jLabel1");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Category:");

        lblCategory.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        lblCategory.setText("Category");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/scrumprojekt/iconPostLil.png"))); // NOI18N

        javax.swing.GroupLayout postOneLayout = new javax.swing.GroupLayout(postOne);
        postOne.setLayout(postOneLayout);
        postOneLayout.setHorizontalGroup(
            postOneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(postOneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(54, 54, 54)
                .addGroup(postOneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(postOneLayout.createSequentialGroup()
                        .addGroup(postOneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblText, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(postOneLayout.createSequentialGroup()
                                .addComponent(authorPostOne)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(datePostOne)))
                        .addGap(0, 197, Short.MAX_VALUE))
                    .addGroup(postOneLayout.createSequentialGroup()
                        .addComponent(headlinePostOne)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)))
                .addGap(18, 18, 18)
                .addGroup(postOneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCategory)
                    .addComponent(dateLastReplyPostOne)
                    .addComponent(lastReplyPostOne))
                .addContainerGap())
        );
        postOneLayout.setVerticalGroup(
            postOneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(postOneLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lastReplyPostOne)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dateLastReplyPostOne)
                .addContainerGap())
            .addGroup(postOneLayout.createSequentialGroup()
                .addGroup(postOneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(headlinePostOne)
                    .addComponent(jLabel1)
                    .addComponent(lblCategory))
                .addGroup(postOneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(postOneLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, postOneLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)))
                .addGroup(postOneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(datePostOne)
                    .addComponent(authorPostOne)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(postOne, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(postOne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel authorPostOne;
    private javax.swing.JLabel dateLastReplyPostOne;
    private javax.swing.JLabel datePostOne;
    private javax.swing.JLabel headlinePostOne;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lastReplyPostOne;
    private javax.swing.JLabel lblCategory;
    private javax.swing.JLabel lblText;
    private javax.swing.JPanel postOne;
    // End of variables declaration//GEN-END:variables
}
