/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package scrumprojekt;

import java.util.HashMap;
import oru.inf.InfDB;

/**
 *
 * @author Joakim
 */
public class postPanel extends javax.swing.JPanel {

    private InfDB db;
    private int post_id;
    private HashMap<String,String> post;
    private HashMap<String,String> user;
    /**
     * Creates new form postPanel
     */
    public postPanel(InfDB db, int post_id) {
        initComponents();
        this.db = db;
        this.post_id = post_id;
        updatePanel();
        //jLabel1.setLocation(27, 20);
        
        
    }
    
    public void updatePanel() {
        post = DBFetcher.fetchPost(db, this.post_id);
        user = DBFetcher.fetchUser(db, Integer.parseInt(post.get("EMPLOYEE_IDEMPLOYEE")));
        
        headlinePostOne.setText(post.get("HEADLINE"));
        datePostOne.setText(post.get("POSTDATE"));
        authorPostOne.setText(user.get("FIRSTNAME") + " " + user.get("LASTNAME"));
        lblCategory.setText(post.get("TAG"));
        
        String postText = post.get("TEXT");
        int postTextLength = postText.length();
        if(postTextLength > 70) {
            lblText.setText(String.copyValueOf(post.get("TEXT").toCharArray(), 0, 70) + "...");
        } else {
            lblText.setText(String.copyValueOf(post.get("TEXT").toCharArray(), 0, postTextLength));
        }
        
        
        
        this.setVisible(true);
    }
    
    public int getPostId() {
        return post_id;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        postOne = new javax.swing.JPanel();
        headlinePostOne = new javax.swing.JLabel();
        imagePostOne = new javax.swing.JLabel();
        authorPostOne = new javax.swing.JLabel();
        datePostOne = new javax.swing.JLabel();
        lastReplyPostOne = new javax.swing.JLabel();
        dateLastReplyPostOne = new javax.swing.JLabel();
        lblText = new javax.swing.JLabel();
        lblCategory = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        postOne.setBackground(new java.awt.Color(250, 249, 246));
        postOne.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        postOne.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headlinePostOne.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        headlinePostOne.setText("Headline:");
        postOne.add(headlinePostOne, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 8, -1, -1));

        imagePostOne.setIcon(new javax.swing.ImageIcon(getClass().getResource("/scrumprojekt/pogu.png"))); // NOI18N
        postOne.add(imagePostOne, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 8, 50, 41));

        authorPostOne.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        authorPostOne.setText("Author");
        postOne.add(authorPostOne, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 55, -1, -1));

        datePostOne.setText("Date and time");
        postOne.add(datePostOne, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, -1, -1));

        lastReplyPostOne.setText("Last reply");
        postOne.add(lastReplyPostOne, new org.netbeans.lib.awtextra.AbsoluteConstraints(666, 27, -1, -1));

        dateLastReplyPostOne.setText("Date and time ");
        postOne.add(dateLastReplyPostOne, new org.netbeans.lib.awtextra.AbsoluteConstraints(666, 55, -1, -1));

        lblText.setText("jLabel1");
        postOne.add(lblText, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 12, 169, -1));

        lblCategory.setText("Catogor");
        postOne.add(lblCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 60, -1, -1));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Category:");
        postOne.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(467, 57, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(postOne, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(postOne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel authorPostOne;
    private javax.swing.JLabel dateLastReplyPostOne;
    private javax.swing.JLabel datePostOne;
    private javax.swing.JLabel headlinePostOne;
    private javax.swing.JLabel imagePostOne;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lastReplyPostOne;
    private javax.swing.JLabel lblCategory;
    private javax.swing.JLabel lblText;
    private javax.swing.JPanel postOne;
    // End of variables declaration//GEN-END:variables
}
